spring.application.name=chronos
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:simulation
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator - expose only health and info endpoints over HTTP
#management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Disable Spring Cloud compatibility checks to run with this Spring Boot version during local development
spring.cloud.compatibility-verifier.enabled=false
